PPD_DEFINITIONS_PATH = "ppd_definitions/"
SOURCE_FILE_PATH = "process_data/source_data/"
TARGET_FILE_PATH = "process_data/target_data/"
JOB_DEFINITIONS_NAME = "ppd_definitions/job_definitions.json"
CONFIG_FILE_NAME = "config.json"
